# -*- coding: utf-8 -*-
"""netflix_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VijaX32chWx4JpsLbUL3KLO4wufNhq0D
"""

# Importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Read in the Netflix CSV as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")


netflix_subsetdf = netflix_df[netflix_df["type"] == "Movie"]
new_df = netflix_subsetdf[(netflix_subsetdf["release_year"] >= 1990) & (netflix_subsetdf["release_year"] < 2000)]
plt.hist(new_df["duration"])
plt.title("Movie Durations in the 90s")
plt.xlabel("Duration(min)")
plt.ylabel("Number of Movies")
plt.show()
duration = 100
action_movies = new_df[new_df["genre"] == "Action"]



short_movie_count = (action_movies["duration"] <90).sum()
print(short_movie_count)